### ISSUE TITLE
建议：添加自动切换第三人称的配置

### ISSUE THREAD

**Issue by Dr-WeiAL** [Snownee/Nimble#14]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

2.2.1

### Modloader version

Forge 40.1.19

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

在坐上一些家具mod的椅子等方块上时会自动切换到第三人称视角

再比如就是被alexsmobs的鳄鱼咬到也会自动切换为第三人称

更多时候并不想让它切换，配置里面只有关掉模组功能才不会自动切换

**Comment by Snownee** [comment]
这个功能1.19再加吧
