### ISSUE TITLE
Suggestion/Enhancement: Re-implement the reverse-third-person perspective?

### ISSUE THREAD

**Issue by TeetoKaziim** [Snownee/Nimble#2]
Currently, it seems like, with this mod installed, I can't shift to the "Looking at the front of my face" perspective vanilla has, the classic minecraft-youtuber "selfie / intro" camera view.

It'd be nice if that could be included. :3

Mod is lovely and smooth. Thanks so much.

**Comment by Snownee** [comment]
Thanks for your suggestion. To be honest I do not know how to implement the front view neatly. The code will be long and hard to be maintained, so I choose to to skip it.

Maybe I will try "press X key to use front view"

**Comment by Fortist** [comment]
I too ask for this because sometimes I need to see whats on the front.

**Comment by heldheld** [comment]
Any chance you'd reconsider trying to add this? It would be an amazing addition to have a smooth front facing third person transition!
