### ISSUE TITLE
Cloth config installed, no settings for Nimble

### ISSUE THREAD

**Issue by Zorklis** [Snownee/Nimble#23]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Mod version

Nimble-1.20.1-fabric-5.0.1

### Modloader version

fabric-loader-0.15.1-1.20.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Anyways I just wish elytra third person wasn't the default.

**Comment by Snownee** [comment]
please install Kiwi

**Comment by Zorklis** [comment]
![firefox_P2Su4g0uVu](https://github.com/Snownee/Nimble/assets/85455465/10d1f177-f741-4d26-b0a1-e4884c8f6e10)
Please don't mislead people in the description then. Just delete the cloth config mention and just keep kiwi.

**Comment by Snownee** [comment]
why? please read

**Comment by Zorklis** [comment]
"In-game config is provided if you have Cloth Config installed" But it's not provided. You clearly need kiwi to do anything.

Other mods do this without kiwi or even Cloth config. The wording on this could be better.

**Comment by Snownee** [comment]
please read. it is a "UI" there

**Comment by Zorklis** [comment]
I'm reading and don't be condescending, it's obviously written that it could be interpreted however you like.
It's pretty silly to need 1 mod to configure settings when users should be able to configure it standalone. Let alone 2 whole mods.

Anyways that's my nitpick.
